# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: book.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'book.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"P\n\x0b\x42ookRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x16\n\x0epublished_year\x18\x04 \x01(\x05\"Q\n\x0c\x42ookResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x16\n\x0epublished_year\x18\x04 \x01(\x05\"\x1b\n\rBookIdRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x12\x42ookDeleteResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xe8\x01\n\x0b\x42ookService\x12\x33\n\nCreateBook\x12\x11.book.BookRequest\x1a\x12.book.BookResponse\x12\x32\n\x07GetBook\x12\x13.book.BookIdRequest\x1a\x12.book.BookResponse\x12\x33\n\nUpdateBook\x12\x11.book.BookRequest\x1a\x12.book.BookResponse\x12;\n\nDeleteBook\x12\x13.book.BookIdRequest\x1a\x18.book.BookDeleteResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKREQUEST']._serialized_start=20
  _globals['_BOOKREQUEST']._serialized_end=100
  _globals['_BOOKRESPONSE']._serialized_start=102
  _globals['_BOOKRESPONSE']._serialized_end=183
  _globals['_BOOKIDREQUEST']._serialized_start=185
  _globals['_BOOKIDREQUEST']._serialized_end=212
  _globals['_BOOKDELETERESPONSE']._serialized_start=214
  _globals['_BOOKDELETERESPONSE']._serialized_end=251
  _globals['_BOOKSERVICE']._serialized_start=254
  _globals['_BOOKSERVICE']._serialized_end=486
# @@protoc_insertion_point(module_scope)
